# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
permalink:           /blog/:categories/:year/:month/:day/:title.html

# Setup
title:               David Ly
tagline:             'All Things Machine Learning / Deep Learning / Computer Vision'

# description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'Machine Learning / Deep Learning / Computer Vision'
url:                 http://www.davidly.com
baseurl:             ''
blogurl:             '/blog'
paginate:            5

# Pagination
paginate_path:       'blog/page:num/'

# About/contact
author:
  name:              David Ly
  url:               http://www.davidly.com
  email:             contact@davidly.com

# Custom vars
version:             1.0.1

#Gems
gems:
  - jekyll-paginate
  - jekyll-assets
  - jekyll-seo-tag

# Compress.html
compress_html:
  comments: ["<!-- ", " -->"]


# jekyll-assets
assets:
  compress:
    js: true
    css: true

  assets:
    - "*.png"
    - "*.jpeg"
    - "*.jpg"

  sources:
    - public/project-images/card-headers
